theme: jekyll-theme-slate
title: Dignum Memoria
description: Filled with attempts at diddling my skittle. Follow for guaranteed drain bamage. 

<script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS_CHTML"></script>
